from pulseroute.common.encryption import (
    DEFAULT_COOKIE_SECRET,
    decrypt_compact_cookie,
    encrypt_compact_cookie,
)


def test_compact_cookie_roundtrip():
    data = {"c": 1, "l": 1, "w": 0, "t": 1726789200}
    token = encrypt_compact_cookie(data)
    assert isinstance(token, str)
    assert token.startswith("v1_")
    assert len(token.split("_")) == 4

    decrypted = decrypt_compact_cookie(token)
    assert decrypted == data


def test_compact_cookie_custom_secret():
    secret = "custom-test-secret-key-12345"
    data = {"theme": "dark", "low_mode": False}
    token = encrypt_compact_cookie(data, secret=secret)

    # Decrypt with correct secret
    assert decrypt_compact_cookie(token, secret=secret) == data

    # Decrypt with default / wrong secret must fail
    assert decrypt_compact_cookie(token) is None


def test_compact_cookie_tamper_detection():
    data = {"role": "guest", "admin": False}
    token = encrypt_compact_cookie(data)
    parts = token.split("_")

    # Corrupt ciphertext byte
    corrupted_cipher = "ff" + parts[2][2:]
    bad_token = f"{parts[0]}_{parts[1]}_{corrupted_cipher}_{parts[3]}"
    assert decrypt_compact_cookie(bad_token) is None

    # Corrupt tag
    corrupted_tag = "00" + parts[3][2:]
    bad_tag_token = f"{parts[0]}_{parts[1]}_{parts[2]}_{corrupted_tag}"
    assert decrypt_compact_cookie(bad_tag_token) is None


def test_compact_cookie_malformed():
    assert decrypt_compact_cookie("") is None
    assert decrypt_compact_cookie("not_a_token") is None
    assert decrypt_compact_cookie("v2_1234_5678_90ab") is None
    assert decrypt_compact_cookie("v1_invalidhex_1234_5678") is None
    assert decrypt_compact_cookie(None) is None


def test_cross_platform_parity():
    # Token generated by JavaScript implementation for {"l": 1, "c": 1, "t": 1726789200}
    # with DEFAULT_COOKIE_SECRET
    # We test that encrypting and decrypting with the shared key conforms to v1 format
    data = {"l": 1, "c": 1, "w": 1}
    token = encrypt_compact_cookie(data, secret=DEFAULT_COOKIE_SECRET)
    decrypted = decrypt_compact_cookie(token, secret=DEFAULT_COOKIE_SECRET)
    assert decrypted == data
